### ISSUE TITLE
How to install with R 3.6

### ISSUE THREAD

**Issue by yuGithuuub** [plger/pipeComp#25]
Hi：
I am not ready to upgrade R to 4.0.0, how can I install a version suitable for R3.6?

ERROR: this R is version 3.6.0, package 'pipeComp' requires R >= 4.0

**Comment by plger** [comment]
Hi,
use
```
BiocManager::install("plger/pipeComp", ref="R3.6")
```
FYI the package was just updated.
Pierre-Luc

**Comment by yuGithuuub** [comment]
Thank you very much, it has been successfully installed.
centOS needs to install V8 in advance.

sudo yum install v8-devel
