### ISSUE TITLE
Issue with doubletmethod in runPipeline()

### ISSUE THREAD

**Issue by cindyfang70** [plger/pipeComp#49]
Hello! Thank you for creating pipeComp, I am really excited to be using it for my project. I'm just getting started and maybe this is an error on my end, but I am coming across an issue with running the pipeline. It seems that when I am running an scrna pipeline, I get the following error: 
```Error in dataset `dataset1` with parameters:
doubletmethod=none, filt=filt.lenient, norm=norm.seurat, sel=sel.vst, selnb=2000, dr=seurat.pca, maxdim=50, clustmethod=clust.seurat, dims=10, k=20, steps=8, resolution=0.01, min.size=50
in step `doublet`, evaluating command:
`pipDef[["doublet"]](x = x, doubletmethod = "none")`
                Error:
Error in negate(.p): argument ".p" is missing, with no default```

My code is essentially the same as what is given [here](https://rdrr.io/github/plger/pipeComp/f/vignettes/pipeComp_scRNA.Rmd): 

```
pip_def <- scrna_pipeline(pipeClass = "sce") 
alternatives <- list(
  doubletmethod=c("none"),
  filt=c("filt.lenient", "filt.stringent"),
  norm=c("norm.seurat", "norm.sctransform", "norm.scran"),
  sel=c("sel.vst"),
  selnb=2000,
  dr=c("seurat.pca"),
  clustmethod=c("clust.seurat"),
  dims=c(10, 15, 20, 30),
  resolution=c(0.01, 0.1, 0.2, 0.3, 0.5, 0.8, 1, 1.2, 2)
)
datasets <- list.files(path="./7-experiment-files", pattern = "(.)*.RDS")
datasets <- paste("7-experiment-files", datasets, sep="/")
dat_list <- lapply(datasets, function (x) readRDS(x))
dat_list <- lapply(dat_list, function(sce) { sce$phenoid <- 0; sce })
res <- runPipeline(dat_list, alternatives, pip_def, nthreads=3)
```

I'm not too sure as to why I am getting this error, but any help would be appreciated. Thank you in advance for your time! 
--Cindy Fang

**Comment by plger** [comment]
Hi,

- I'll need the package and Bioconductor versions.
- Did you load `scrna_alternatives.R`? 
- The pipeline evaluation won't work if you don't have some truth (i.e. `phenoid`).

Pierre-Luc

**Comment by cindyfang70** [comment]
Hello, and thank you for your reply. 

- I am on pipeComp version 1.0.0  and Bioconductor 3.11. 
- It turns out it was my mistake and I didn't load scrna_alternatives.R! I've loaded it now and get the following error when running: 
``` 
Error in dataset `dataset7` with parameters:
doubletmethod=none, filt=filt.stringent, norm=norm.scran, sel=sel.vst, selnb=2000, dr=seurat.pca, maxdim=50, clustmethod=clust.seurat, dims=30, k=20, steps=8, resolution=2, min.size=50
in step `filtering`, evaluating command:
`pipDef[["filtering"]](x = x, filt = "filt.stringent")`
                Error:
Error in h(simpleError(msg, call)): error in evaluating the argument 'x' in selecting a method for function 'which': first argument must be a vector 
```
Is this because I don't have anything like phenoid that i'm passing in? Thanks again for your help and sorry for any inconvenience! 

--Cindy

**Comment by plger** [comment]
that will certainly create errors, but an easy way to test it would be to assign a random phenoid to your datasets and re-run.
