### ISSUE TITLE
Metadata names

### ISSUE THREAD

**Issue by cindyfang70** [plger/pipeComp#50]
Hello,

Thank you so much for creating this useful package. One thing I have noticed is that the add_meta() function in scrna_alternatives.R calculates two metrics called pct_Mt and percent_top_20. However, the runPipeline() function looks for metrics called pct_counts_Mt and pct_counts_in_top_20_features. Is it possible that the add_meta() function names these metrics incorrectly? 

Thanks for taking the time to read this! 
Cindy

**Comment by plger** [comment]
Hi,
The scatter package renamed its output variables a few times lately... can you tell me which version of `scater` and of `pipeComp` you're using?

**Comment by cindyfang70** [comment]
Hello, 

Thanks for getting back to me! I am using pipeComp 1.0.0 and scater 1.16.2.

**Comment by plger** [comment]
Right, now you see why this is a pain to maintain compatibility :)
I've pushed a change which will hopefully ensure compatibility with the different scater versions (so far!), you can install with
`BiocManager::install("plger/pipeComp")`
(or else just download and source the new `scrna_alternatives.R`)
Let me know if you still have the problem,
Pierre-Luc

**Comment by plger** [comment]
Hi @cindyfang70 , can you confirm whether the update solved your isue?

**Comment by cindyfang70** [comment]
Hi, sorry for the late reply! I believe in scater 1.18.3, the percentage of counts in top 20 features is actually named percent.top_20, so this part is still causing issues for me as pipecomp looks for pct_counts_in_top_20_features.

**Comment by plger** [comment]
but this 'percent.top_20' should be renamed in the wrappers, are you sure you're using the latest github version?

**Comment by cindyfang70** [comment]
Yes, my mistake, sorry about the confusion. Thank you for your help on this issue!
